### ISSUE TITLE
ParserError "Unexpected input: .sum()" when using aggregate functions with TypeScript

### ISSUE THREAD

**Issue by stefan-girlich** [supabase/postgrest-js#523] opened 2024-03-11 14:59 UTC
# Bug report
- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When I use aggregate functions, the inferred TypeScript data type will always depict an error, requiring me to use casts to `any`.

## To Reproduce

```ts
  const { data } = await supabase.from("things").select(`
    field.sum(),
    ...other_things(id, name, color)
  `);
```

The inferred type for `data` seen in my VS Code is:
```ParserError<"Unexpected input: .sum(),\n    ...other_things(id, name, color)\n  ">[] | null```

Inference works fine when not using aggregate functions.
Re-generating TS types via `supabase gen types typescript` does not fix the issue.

## Expected behavior
Types should be inferred correctly without an error.

## System information

- OS: MacOS
- Version of supabase-js: 2.39.7
- Version of Node.js: 21.6.2

**Comment by stefan-girlich** [comment] 2024-04-10 12:17
A brief update after upgrading `supabase-js` from 2.39.7 to 2.42.0:

Error in TypeScript type is now as following for the same original code:
```ts
const data: SelectQueryError<"Referencing missing column `sum`">[] | null
```

`@supabase/postgrest-js` is at v1.15.0, so the fix for #447 should already be included.
Am I maybe missing something?

**Comment by stefan-girlich** [comment] 2024-04-10 17:12
@bnjmnt4n I added [test cases](https://github.com/supabase/postgrest-js/commit/8ba7b3e846f24d9c07a3dfb7224077acce379adc) which currently fail at compile-time.

**Comment by bnjmnt4n** [comment] 2024-04-15 14:34
@stefan-girlich thanks for providing the examples; I'm really busy now so I can probably look at them next week only.

**Comment by stefan-girlich** [comment] 2024-05-29 07:50
@bnjmnt4n Would you know if this is scheduled already? Thanks!

**Comment by stefan-girlich** [comment] 2024-08-21 08:32
@bnjmnt4n Would you know more? I can look into a solution/PR myself, but I'd be happy about some guidance concerning how to tackle this.

**Comment by sanjaybaskaran01** [comment] 2024-08-27 11:22
Is this resolved? Facing the same issue here.

**Comment by veloware** [comment] 2024-09-17 14:19
@sanjaybaskaran01 dont think it has been resolved, im also seeing the same when trying to use `sum()`

**Comment by avallete** [comment] 2024-10-29 11:31
The fix has been released in `supabase-js` v2.46.0. I'm closing this issue, but feel free to reopen if you encounter any further errors.

**Closed by avallete** 2024-10-29 11:31 UTC
Labels: bug

**Comment by cohlar** [comment] 2024-10-30 06:48
Hi @avallete,

Thanks for the update! I was excited to upgrade to `2.46.0`, but it seems to be causing another issue: in the below code, the type inferred to `data` is `string[]`.

```ts
const { data, error } = await supabase
          .schema('not_public')
          .from('my_table')
          .select('seller, ...sellers(code)')
          .match({ region });
if (error) throw error;
```

The inferred `data` type is correct either:
- when I remove `, ...sellers(code)`
- or when I downgrade back to `2.45.5`

I'm writing this here because I have a feeling this issue is related to the fix of aggregate functions (if not, happy to create a new issue for this).

Thanks

**Comment by avallete** [comment] 2024-10-30 07:11
Hey @cohlar do you think you could submit a request trough the supabase support, or if it isn't sensitive provide those infos for debugging:

1. The `supbase.ts` containing the `Database` types generations for your database
2. The exact query that is causing issue (I guess `my_table` is a replacement).

That way we can reproduce on our end and get this fixed.

**Comment by cohlar** [comment] 2024-10-30 08:02
I created a case with supabase support ✅

**Comment by cohlar** [comment] 2024-10-30 16:55
> Hi @avallete,
> 
> Thanks for the update! I was excited to upgrade to `2.46.0`, but it seems to be causing another issue: in the below code, the type inferred to `data` is `string[]`.
> 
> ```ts
> const { data, error } = await supabase
>           .schema('not_public')
>           .from('my_table')
>           .select('seller, ...sellers(code)')
>           .match({ region });
> if (error) throw error;
> ```
> 
> The inferred `data` type is correct either:
> 
> * when I remove `, ...sellers(code)`
> * or when I downgrade back to `2.45.5`
> 
> I'm writing this here because I have a feeling this issue is related to the fix of aggregate functions (if not, happy to create a new issue for this).
> 
> Thanks

This now seems fixed on version `2.46.1` 👍 
Thank you!

**Comment by we-ink** [comment] 2024-11-14 21:51
Still not working in `2.46.1` to me :/

<img width="639" alt="Screenshot 2024-11-14 at 22 48 26" src="https://github.com/user-attachments/assets/adbdf5ad-fc3d-4675-bca7-90dec16526eb">

**Comment by avallete** [comment] 2024-11-15 08:44
> Still not working in `2.46.1` to me :/
> 
> <img alt="Screenshot 2024-11-14 at 22 48 26" width="639" src="https://private-user-images.githubusercontent.com/168749358/386379682-adbdf5ad-fc3d-4675-bca7-90dec16526eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NjAzOTYsIm5iZiI6MTczMTY2MDA5NiwicGF0aCI6Ii8xNjg3NDkzNTgvMzg2Mzc5NjgyLWFkYmRmNWFkLWZjM2QtNDY3NS1iY2E3LTkwZGVjMTY1MjZlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQwODQxMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTdiMmI1MzM2ODM1ZDk3Y2FlMmYyZTcwMTUwNTU0OWJiN2UxNzEyYWU4ZmY0YTNlYjYzZmU5Nzc0Mjg5Zjc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GyqGwLEoIPQ-YS-otYasoGzfbQy3z4I_5ZUA7_wWqGM">

Hey @we-ink 

Sadly the fixes did some unexpected breaking changes on some codebases. That's the reason why we reverted in 2.46.1 and we are currently considering it as a breaking change and releasing it following the release candidate procedure to let people the time to migrate. Please try the `2.46.2-rc.3` as recommended here: https://github.com/orgs/supabase/discussions/30324
