### ISSUE TITLE
select avg() in query

### ISSUE THREAD

**Issue by Nielsien** [supabase/postgrest-js#199] opened 2021-07-28 08:19 UTC
# Feature request
A way to fetch the average of a given query and field, without the need to create a rcp function to calculate the avg.

## Describe the solution you'd like
Something like the count option in the select function at the moment:
`this.supabase.from('table').select('value', { avg: 'value' });`
And maybe give the field you want the average of as a parameter for the select properties

## Describe alternatives you've considered
Creating an rcp which you can call to calculate an average for a field and table

**Comment by soedirgo** [comment] 2021-08-11 16:10
Closing this as duplicate of https://github.com/supabase/postgrest-js/issues/206

**Closed by soedirgo** 2021-08-11 16:10 UTC
