### ISSUE TITLE
Queries using !inner are returning null in the supabase-js(reduce many-to-many relationships detected)

### ISSUE THREAD

**Issue by gabrielsestrem** [supabase/postgrest-js#264] opened 2022-04-09 20:59 UTC
# Bug report

## Describe the bug

All my queries using inner joins are returning null.

This is CRITICAL as we have many queries like this in the grid (filtering results)

I am quite sure this is an issue, because we haven't had any new release and these two queries are active for months working well.

Please, Check this ASAP!

I can give you two examples that are returning null when using inner joins:

```    const { data: reverse_orders, count, error } = await supabase
    .from('reverse_orders')
    .select(
        `id,
        client:client_id(name, email),
        status:status_id(name, id),
        reverse_trackings!inner(courier_collect_number, customer_posting, courier_company),
        ecommerce_number, date_request, date_analyzed, date_finished, price, refund_value, exchange_value, is_exception`, 
        { count: "exact" }
    )
    .eq('organisation_id', organisationId)
    .eq('reverse_trackings.courier_collect_number', collectNumber)



       query = supabase
            .from('reverse_orders')
            .select(
                `id,
                client:client_id(name, email),
                status:status_id(name, id),
                reverse_trackings!inner(courier_collect_number, customer_posting, courier_company),
                ecommerce_number, date_request, date_analyzed, date_finished, price, refund_value, exchange_value, is_exception`, 
                { count: "exact" }
            )
            .eq('organisation_id', organisationId)
            .eq('reverse_trackings.customer_posting', !isCollect)
            .match(filter)

**Comment by steve-chavez** [comment] 2022-04-10 16:09
@gabrielsestrem Can you send me your project ref to steve@supabase.io?

**Comment by gabrielsestrem** [comment] 2022-04-10 16:36
Hi @steve-chavez. Done!

**Comment by gabrielsestrem** [comment] 2022-04-10 17:14
Hi @steve-chavez . I am thinking about creating views using the INNER JOIN in the database and then querying from the view. What's your opinion about that? Tomorrow is Monday and customers will start to complain if we don't fix this by tomorrow.

**Comment by steve-chavez** [comment] 2022-04-10 18:30
@gabrielsestrem yes views are fine as well. If you're using RLS, make sure to alter the owner like discussed here: https://github.com/supabase/supabase/discussions/1501

Hm, from our side, there was no change on the `!inner` logic.

>  returning null in the supabase-js 

Does it return `null` or an empty array `[]`? Does the error field show something?

**Comment by gabrielsestrem** [comment] 2022-04-11 08:56
Hi @steve-chavez. it does return `null` and thanks for asking for the error field. Now I can see what's happening.

`reverseDetailsForStateError {
  message: "Could not embed because more than one relationship was found for 'reverse_orders' and 'addresses'",
  details: [
    {
      relationship: 'reverse_orders_address_id_fkey[address_id][id]',
      embedding: 'reverse_orders with addresses',
      cardinality: 'many-to-one'
    },
    {
      relationship: 'public.view_reverse_items[reverse_itens_reverse_order_id_fkey][reverse_orders_address_id_fkey]',
      embedding: 'reverse_orders with addresses',
      cardinality: 'many-to-many'
    },
    {
      relationship: 'public.view_reverse_items[reverse_items_reverse_order_id_fkey][reverse_orders_address_id_fkey]',
      embedding: 'reverse_orders with addresses',
      cardinality: 'many-to-many'
    }
  ],
  hint: "Try changing 'addresses' to one of the following: 'addresses!reverse_orders_address_id_fkey', 'addresses!view_reverse_items', 'addresses!view_reverse_items'. Find the desired relationship in the 'details' key."
}`

All of these started when I created a view called view_reverse_items. This view has six inner joins and after creating the view, all the other  !inner joins in supabase-js failed. If I drop the view, everything started to work again.

What is wrong with that view?

`CREATE VIEW view_reverse_items AS
SELECT
	reverse_items.received,
       reverse_items.created_at,
	reverse_items.sku,
	reverse_items.description,
	reverse_items.image_url,
	reverse_items.quantity,
	reverse_items.price,
	reverse_items.reason,
	reverse_items.is_exchange,
	reverse_items.id_item,
       reverse_items.organisation_id,
	reverse_orders.ecommerce_number,
       reverse_orders.created_at as reverse_orders_created_at,
	reverse_orders.price as reverse_orders_price,
	reverse_orders.refund_value,
	reverse_orders.exchange_value,
	reverse_orders.is_exception,
       reverse_orders.status_id,
	reverse_orders.client_id,
	reverse_orders.address_id,
	reverse_orders.reverse_tracking_id,
	reverse_order_id,
	reverse_status.name as reverse_status_name,
	reverse_trackings.courier_company,
	reverse_trackings.shipping_company_id,
	shipping_company.name as shipping_company_name,
	clients.name,
	addresses.city,
	addresses.state
FROM
	reverse_items
INNER JOIN reverse_orders ON reverse_order_id = reverse_orders.id
INNER JOIN reverse_status ON reverse_orders.status_id = reverse_status.id
INNER JOIN reverse_trackings ON reverse_orders.reverse_tracking_id = reverse_trackings.id
INNER JOIN shipping_company ON reverse_trackings.shipping_company_id = shipping_company.id
INNER JOIN clients ON reverse_orders.client_id = clients.id
INNER JOIN addresses ON reverse_orders.address_id = addresses.id`

**Comment by gabrielsestrem** [comment] 2022-04-11 09:13
Hi @steve-chavez. I think now I understand,

If I have views using INNER JOIN, every time I want to use supabase-js inner feature, I have to specify which FK I am referring to.

Instead of doing: `reverse_trackings!inner`
I have to do: `reverse_trackings!reverse_orders_reverse_tracking_id_fkey`

Is it correct?

**Comment by steve-chavez** [comment] 2022-04-11 18:03
> What is wrong with that view?

Nothing wrong. Here I think the problem is on us. Specifically, the REST API(PostgREST) is being too liberal in detecting many-to-many relationships to other tables/views(as it can be seen in the [error you shared above](https://github.com/supabase/postgrest-js/issues/264#issuecomment-1094748395), it's considering the `view_reverse_items` as a junction). I'm currently working on a patch, with this there would be only one relationship detected between `reverse_orders` and `addresses`.

> Instead of doing: reverse_trackings!inner
> I have to do: reverse_trackings!reverse_orders_reverse_tracking_id_fkey
> Is it correct?

Oh, seems it should be: `reverse_trackings!reverse_orders_reverse_tracking_id_fkey!inner` the hints in the error message do not include the `!inner` part.

**Comment by gabrielsestrem** [comment] 2022-04-11 19:47
Are you able to apply the patch in both projects? we have two: prod and test. I'll send you an email with our project refs. Thanks @steve-chavez

**Comment by gabrielsestrem** [comment] 2022-04-18 12:25
Hi @steve-chavez . Any updates on this?
Thanks,
Gabriel

**Comment by steve-chavez** [comment] 2022-04-19 04:49
@gabrielsestrem Yes, I'm still working on this one. 

It requires some heavy refactoring(https://github.com/PostgREST/postgrest/pull/2250) but it should be done by this week.

**Comment by steve-chavez** [comment] 2022-04-23 18:41
@gabrielsestrem Sorry for the delay. https://github.com/PostgREST/postgrest/pull/2262 should be merged Monday tops and then I'll make a pre-release and patch your instance.

**Comment by gabrielsestrem** [comment] 2022-04-23 19:07
Thanks @steve-chavez 🙏🏼

**Comment by steve-chavez** [comment] 2022-04-26 03:23
@gabrielsestrem Just updated both the instances you shared through email. Let me know if the error goes away.

**Comment by steve-chavez** [comment] 2022-04-27 16:35
On the postgrest side it was [confirmed](https://github.com/PostgREST/postgrest/issues/2070#issuecomment-1111045734) that it resolved a similar issue(unnecessary many-to-many relationships are no longer generated) 

So considering this one resolved - but please reopen if not.

**Closed by steve-chavez** 2022-04-27 16:35 UTC
Labels: bug

**Comment by gabrielsestrem** [comment] 2022-04-27 17:29
Hi @steve-chavez it's working now! thanks a lot man! will this work in a new projects as well?

**Comment by steve-chavez** [comment] 2022-04-28 00:52
@gabrielsestrem Great to know!

>  will this work in a new projects as well?

Not yet, but the change should be rolled to other projects next week.

**Comment by gabrielsestrem** [comment] 2022-04-28 12:53
Thanks

**Comment by gabrielsestrem** [comment] 2022-05-30 12:03
Hi @steve-chavez ! I think we might have to reopen this issue.

Suddenly our projects started to get the issue again. I had to drop the view in order to make our queries using !inner joint to work.


` {
  message: "Could not embed because more than one relationship was found for 'reverse_orders' and 'reverse_trackings'",
  details: [
    {
      relationship: 'reverse_orders_reverse_tracking_id_fkey[reverse_tracking_id][id]',
      embedding: 'reverse_orders with reverse_trackings',
      cardinality: 'many-to-one'
    },
    {
      relationship: 'public.view_reverse_items[reverse_items_reverse_order_id_fkey][reverse_orders_reverse_tracking_id_fkey]',
      embedding: 'reverse_orders with reverse_trackings',
      cardinality: 'many-to-many'
    },
    {
      relationship: 'public.view_reverse_items[reverse_itens_reverse_order_id_fkey][reverse_orders_reverse_tracking_id_fkey]',
      embedding: 'reverse_orders with reverse_trackings',
      cardinality: 'many-to-many'
    }
  ],
  hint: "Try changing 'reverse_trackings' to one of the following: 'reverse_trackings!reverse_orders_reverse_tracking_id_fkey', 'reverse_trackings!view_reverse_items', 'reverse_trackings!view_reverse_items'. Find the desired relationship in the 'details' key."
}`

**Comment by gabrielsestrem** [comment] 2022-05-30 12:05
@steve-chavez Just to note, everything was working all right, but started to fail again since Yesterday. And We haven't done any database changes.

**Comment by steve-chavez** [comment] 2022-05-30 18:57
@gabrielsestrem Sorry about this, there was a middleware migration recently and this didn't pick up your patched postgREST.
This will not happen again as we'll now use the [latest pre-release](https://github.com/PostgREST/postgrest/releases/tag/v9.0.0.20220516) for all instances.

I've patched both projects you shared me through email. Let me know if that fixes the issue.

**Comment by gabrielsestrem** [comment] 2022-05-30 21:48
Hi Steve, We now have three projects, let me send you all the three projects IDS by email
