### ISSUE TITLE
supabase-js rpc call error:  message: 'a column definition list is required for functions returning "record"'

### ISSUE THREAD

**Issue by bbagherian** [supabase/postgrest-js#453] opened 2023-07-26 15:28 UTC
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Following this documentation leads to an error on `rpc` call: https://supabase.com/docs/guides/database/extensions/postgis 

```js
{
    "code": "42601",
    "details": null,
    "hint": null,
    "message": "a column definition list is required for functions returning \"record\""
}
```

## To Reproduce

SQL on the website dashboard: 

```sql
create table if not exists public.restaurants (
	id int generated by default as identity primary key,
	name text not null,
	location geography(POINT) not null
);

create index restaurants_geo_index
  on public.restaurants
  using GIST (location);

insert into public.restaurants
  (name, location)
values
  ('Supa Burger', st_point(-73.946823, 40.807416)),
  ('Supa Pizza', st_point(-73.94581, 40.807475)),
  ('Supa Taco', st_point(-73.945826, 40.80629));


create or replace function nearby_restaurants(lat float, long float)
returns setof record
language sql
as $$
  select id, name, st_astext(location) as location, st_distance(location, st_point(long, lat)::geography) as dist_meters
  from public.restaurants
  order by location <-> st_point(long, lat)::geography;
$$;

```

and now in the app:
```js
const { data, error } = await supabase.rpc('nearby_restaurants', {
  lat: 40.807313,
  long: -73.946713,
})

console.log('rpc restaurant', data, error);
```

## Expected behavior

List of results

## Screenshots

![image](https://github.com/supabase/supabase/assets/19957924/0b44f4c9-fa5a-42a2-8aec-0c19c6eb1168)

## System information

- OS: [windows]
- Browser (if applies) [chrome]
- Version of supabase-js: [2.26.0]
- Version of Node.js: [18.16.1]

**Comment by steve-chavez** [comment] 2023-07-27 05:17
> Running as query is ok by the way

Try it in SQL as:

```sql
select * from nearby_restaurants(40, -73);
```

And you'll see it fail in the same way as the RPC.

`ERROR:  a column definition list is required for functions returning "record"`

---

When you declare a `SETOF` function, it is a table-valued function and thus a `SELECT * FROM func()` is the most suitable query for it.

Additionally:

- look at the `select nearby_restaurants()` result. It has the tuple format `(3, \"..)` which is not suitable for a web application.
- If you don't declare types for your table-valued function, then typescript types can't also be generated (@soedirgo CMIIW).

---

Although a better error message could be generated.

**Comment by steve-chavez** [comment] 2023-07-27 21:43
The root cause of this issue seems to be this guide https://supabase.com/docs/guides/database/extensions/postgis#order-by-distance

This [discussion](https://github.com/orgs/supabase/discussions/16075) reports it used to work before? Will check that out.

**Comment by steve-chavez** [comment] 2023-07-28 05:07
Tracking this on https://github.com/PostgREST/postgrest/issues/2881

**Comment by steve-chavez** [comment] 2023-07-28 18:02
I'll fix this on https://github.com/PostgREST/postgrest/issues/2881 and go back to the previous behavior. So this worked before because PostgREST considered a `setof record` as scalar to avoid OP's error.

However this method has the disadvantage of not being able to `select` particular columns from it:

```sql
create or replace function setof_record() returns setof record as $$
  select * from projects;
$$ language sql;
```

```sql
curl 'localhost:3000/rpc/setof_record?select=id'
{"code":"42703","details":null,"hint":null,"message":"column setof_record.id does not exist"}
```

Considering that, it would be better to fix the PostGIS guide to use this function signature:

```sql
create or replace function nearby_restaurants(lat float, long float)
returns TABLE (id public.restaurants%TYPE, name public.restaurants%TYPE, location text, dist_meters float)
language sql
as $$
  select id, name, st_astext(location) as location, st_distance(location, st_point(long, lat)::geography) as dist_meters
  from public.restaurants
  order by location <-> st_point(long, lat)::geography;
$$;
```

The above should work on the current version.

**Comment by srht** [comment] 2023-08-08 07:34
> I'll fix this on [PostgREST/postgrest#2881](https://github.com/PostgREST/postgrest/issues/2881) and go back to the previous behavior. So this worked before because PostgREST considered a `setof record` as scalar to avoid OP's error.
> 
> However this method has the disadvantage of not being able to `select` particular columns from it:
> 
> ```sql
> create or replace function setof_record() returns setof record as $$
>   select * from projects;
> $$ language sql;
> ```
> 
> ```sql
> curl 'localhost:3000/rpc/setof_record?select=id'
> {"code":"42703","details":null,"hint":null,"message":"column setof_record.id does not exist"}
> ```
> 
> Considering that, it would be better to fix the PostGIS guide to use this function signature:
> 
> ```sql
> create or replace function nearby_restaurants(lat float, long float)
> returns TABLE (id public.restaurants%TYPE, name public.restaurants%TYPE, location text, dist_meters float)
> language sql
> as $$
>   select id, name, st_astext(location) as location, st_distance(location, st_point(long, lat)::geography) as dist_meters
>   from public.restaurants
>   order by location <-> st_point(long, lat)::geography;
> $$;
> ```
> 
> The above should work on the current version.

Thanks for the solution. Btw I changed a little this because it was returning invalid sql error then I removed public schema name and wrote types hardcoded instead of variables (%TYPE) and here it's:

```
create or replace function nearby_restaurants(lat float, long float)
returns TABLE (id int, name varchar, location text, dist_meters float)
language sql
as $$
  select id, name, st_astext(location) as location, st_distance(location, st_point(long, lat)::geography) as dist_meters
  from restaurants
  order by location <-> st_point(long, lat)::geography;
$$;
```

**Comment by steve-chavez** [comment] 2023-08-14 23:03
FYI, this is already fixed on [PostgREST v11.2.0](https://github.com/PostgREST/postgrest/releases/tag/v11.2.0) (not deployed to Supabase yet).

**Comment by steve-chavez** [comment] 2023-08-17 18:42
Deploy with the fix is already approved https://github.com/supabase/postgres/pull/720. 

Additionally the docs have been updated https://github.com/supabase/supabase/pull/16177

**Closed by steve-chavez** 2023-08-17 18:42 UTC
Labels: bug, postgrest-patch-needed

**Comment by KA-devl** [comment] 2023-08-20 17:29
Hello, i have this problem that suddenly appear on my app. When will the fix be deployed in supabase?
