### ISSUE TITLE
Foreign Key ambiguity on views

### ISSUE THREAD

**Issue by roker15** [supabase/postgrest-js#229] opened 2021-12-04 05:36 UTC
I see a ciritical issue in making query with supabase is **`ambiguity`** when i have to refer foreign kyes. Even if you don't touch your current tables and Just create a **`view`**. It might break all your api call in your application. Never faced this kind of problem when was using hibernate in java. What u people doing about this. This is i think most critical thing for u guys. Just one change in database and everything is borken.

**Comment by steve-chavez** [comment] 2021-12-04 18:32
Moving to postgrest-js because it seems related to https://postgrest.org/en/v9.0/api.html#embedding-disambiguation.

> Even if you don't touch your current tables and Just create a view.

Do you have a reproducible example(DDL) we can try?

**Comment by steve-chavez** [comment] 2022-04-14 13:34
Relating this to https://github.com/supabase/supabase/discussions/6274#discussioncomment-2517906

**Comment by steve-chavez** [comment] 2022-06-08 00:33
This was solved in https://github.com/PostgREST/postgrest/issues/2277. New views won't break previous requests.

**Closed by steve-chavez** 2022-06-08 00:33 UTC
Labels: postgrest-patch-needed
