### ISSUE TITLE
Error is an empty array when no results

### ISSUE THREAD

**Issue by nicholaschiang** [supabase/postgrest-js#202] opened 2021-08-03 21:10 UTC
# Bug report

## Describe the bug

The `error` is an empty array when there are no results for a query while `data` is `null` (which should be an empty array).

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Run a query using `select()` that returns no results.
2. Notice that `data` is `null`.
3. Notice that `error` is an empty array.

```typescript
const { data, error, count } = await supabase.from<User>('users').select().eq('name', 'no-user-named-this');
console.log(data); // Is `null` instead of an empty array.
console.log(error); // Is an empty array instead of `null`.
console.log(count); // Is `null` instead of zero.
```

## Expected behavior

When a `select` doesn't return any data:
- `data` should be an empty array
- `count` should be zero
- `error` should be `null`

## System information

- OS: Ubuntu 20.04 LTS
- Version of supabase-js: 1.21.0
- Version of Node.js: 12.18.3

**Comment by nicholaschiang** [comment] 2021-08-03 21:14
Current workaround is to detect if `error` is an array like so:
```typescript
const { data, error, count } = await supabase.from<User>('users').select().eq('name', 'no-user-named-this');
if (error instanceof Array) return { results: [], hits: 0 };
if (error) throw new Error(error.message);
return { results: data, hits: count };
```

**Comment by soedirgo** [comment] 2021-08-04 03:06
Hmm, I couldn't reproduce this on my side. I've added a [new test case](https://github.com/supabase/postgrest-js/blob/4de56c2245bb43842f0608f4dde94e9c2db51eb8/test/basic.ts#L281-L293) to cover this - can you run `npm ci && npm t` on this repo and see if it passes? (will need to have the Docker daemon running)

**Comment by steve-chavez** [comment] 2021-11-23 18:07
Closing for now since we can't reproduce and seems to be working fine. If the issue persists, please reopen.

**Closed by steve-chavez** 2021-11-23 18:07 UTC
Labels: bug
